// Downloads the Google Fonts we use into client/public/fonts/ and writes a
// local fonts.css, so the app serves fonts from its own origin (no Google CDN
// request → no visitor IP sent to Google). Re-run if the font set changes.
//
//   node scripts/fetch-fonts.mjs
//
// Commit the resulting client/public/fonts/ so the Docker build ships them.

import { writeFileSync, mkdirSync } from 'fs';
import https from 'https';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800' +
  '&family=JetBrains+Mono:wght@300;400;500;700&family=Monoton&family=Unbounded:wght@400;700;900&display=swap';

// A modern-browser UA makes the API return woff2 (its smallest, best-supported format).
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const OUT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'client', 'public', 'fonts');

function get(url, binary = false) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': UA } }, (r) => {
      if (r.statusCode >= 300 && r.statusCode < 400 && r.headers.location) {
        return get(r.headers.location, binary).then(resolve, reject);
      }
      const chunks = [];
      r.on('data', (c) => chunks.push(c));
      r.on('end', () => resolve(binary ? Buffer.concat(chunks) : Buffer.concat(chunks).toString('utf8')));
    }).on('error', reject);
  });
}

const css = await get(CSS_URL);
mkdirSync(OUT_DIR, { recursive: true });

const urls = [...new Set([...css.matchAll(/https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2/g)].map((m) => m[0]))];
let localCss = '/* Self-hosted Google Fonts — generated by scripts/fetch-fonts.mjs. Do not edit. */\n' + css;

for (const u of urls) {
  const name = u.split('/').pop();
  const buf = await get(u, true);
  writeFileSync(join(OUT_DIR, name), buf);
  localCss = localCss.split(u).join('./' + name);
  console.log('downloaded', name, buf.length, 'bytes');
}

writeFileSync(join(OUT_DIR, 'fonts.css'), localCss);
console.log(`\nwrote fonts.css referencing ${urls.length} local woff2 files into client/public/fonts/`);
